//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UIFramework.Core;

namespace UIFramework.Editor.Demo.SimpleWindow
{
    using System;
    using UnityEngine;
    
    
    [UIFramework.UIAttribute(Uxml="Packages/com.uitoolkit.uiframework/Editor/Demo/SimpleWindow/SimplePanel.uxml", Uss="Packages/com.uitoolkit.uiframework/Editor/Demo/SimpleWindow/SimplePanel.uss")]
    public partial class SimplePanel : EPanel
    {
        
        public UnityEngine.UIElements.Label LabelID;
        
        public UnityEngine.UIElements.ProgressBar ProgressBar;
        
        public UnityEditor.UIElements.ObjectField ObjectField;
        
        public UnityEngine.UIElements.BoundsIntField BoundsIntField;
        
        public UnityEngine.UIElements.Vector2Field Vector2Field;
        
        public UnityEngine.UIElements.Vector3Field Vector3Field;
        
        public UnityEngine.UIElements.Vector4Field Vector4Field;
        
        public UnityEditor.UIElements.ColorField ColorField;
        
        public UnityEditor.UIElements.CurveField CurveField;
        
        public UnityEditor.UIElements.GradientField GradientField;
        
        public UnityEngine.UIElements.EnumField EnumField;
        
        public UnityEditor.UIElements.TagField TagField;
        
        public UnityEditor.UIElements.MaskField MaskField;
        
        public UnityEditor.UIElements.LayerField LayerField;
        
        public UnityEditor.UIElements.LayerMaskField LayerMaskField;
        
        public UnityEditor.UIElements.PropertyField PropertyField;
        
        public SimplePanel(UnityEngine.UIElements.TemplateContainer container) : 
                base(container)
        {
            LabelID = Q<UnityEngine.UIElements.Label>("LabelID");
            ProgressBar = Q<UnityEngine.UIElements.ProgressBar>("ProgressBar");
            ObjectField = Q<UnityEditor.UIElements.ObjectField>("ObjectField");
            BoundsIntField = Q<UnityEngine.UIElements.BoundsIntField>("BoundsIntField");
            Vector2Field = Q<UnityEngine.UIElements.Vector2Field>("Vector2Field");
            Vector3Field = Q<UnityEngine.UIElements.Vector3Field>("Vector3Field");
            Vector4Field = Q<UnityEngine.UIElements.Vector4Field>("Vector4Field");
            ColorField = Q<UnityEditor.UIElements.ColorField>("ColorField");
            CurveField = Q<UnityEditor.UIElements.CurveField>("CurveField");
            GradientField = Q<UnityEditor.UIElements.GradientField>("GradientField");
            EnumField = Q<UnityEngine.UIElements.EnumField>("EnumField");
            TagField = Q<UnityEditor.UIElements.TagField>("TagField");
            MaskField = Q<UnityEditor.UIElements.MaskField>("MaskField");
            LayerField = Q<UnityEditor.UIElements.LayerField>("LayerField");
            LayerMaskField = Q<UnityEditor.UIElements.LayerMaskField>("LayerMaskField");
            PropertyField = Q<UnityEditor.UIElements.PropertyField>("PropertyField");
        }
    }
}
