//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UIFramework.Core;
using UnityEngine;
using UnityEngine.UIElements;
namespace UIFramework.Editor.Utility.GenUICode
{
    [UIFramework.UIAttribute(Uxml = "Packages/com.uitoolkit.uiframework/Editor/Utility/GenUICode/GenUIPanel.uxml",
        Uss="Packages/com.uitoolkit.uiframework/Editor/Utility/GenUICode/GenUIPanel.uss")]
    public partial class GenUIPanel : EPanel
    {
        
        public VisualElement Root;
        
        public VisualElement Hierarchy;
        
        public VisualElement HierarchyTitle;
        
        public ScrollView RootView;
        
        public VisualElement CutLine;
        
        public VisualElement Inspector;
        
        public VisualElement InspectorTitle;
        
        public TextField NameSpace;
        
        public VisualElement InspectorFoot;
        
        public Button Generate;
        
        public GenUIPanel(TemplateContainer container) : base(container)
        {
            Root = Q<VisualElement>("root");
            Hierarchy = Q<VisualElement>("hierarchy");
            HierarchyTitle = Q<VisualElement>("hierarchy_title");
            RootView = Q<ScrollView>("root_view");
            CutLine = Q<VisualElement>("cut_line");
            Inspector = Q<VisualElement>("inspector");
            InspectorTitle = Q<VisualElement>("inspector_title");
            NameSpace = Q<TextField>("name_space");
            InspectorFoot = Q<VisualElement>("inspector_foot");
            Generate = Q<Button>("generate");
        }
    }
}
