//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace UIFramework.Utility.GenUICode
{
    [UIFramework.UIAttribute(Uxml = "Packages/com.uitoolkit.uiframework/Editor/Utility/GenUICode/GenUIPanel.uxml",
        Uss="Packages/com.uitoolkit.uiframework/Editor/Utility/GenUICode/GenUIPanel.uss")]
    public partial class GenUIPanel : Editor.Core.TUIElement
    {
        
        public UnityEngine.UIElements.VisualElement Root;
        
        public UnityEngine.UIElements.VisualElement Hierarchy;
        
        public UnityEngine.UIElements.VisualElement HierarchyTitle;
        
        public UnityEngine.UIElements.ScrollView RootView;
        
        public UnityEngine.UIElements.VisualElement CutLine;
        
        public UnityEngine.UIElements.VisualElement Inspector;
        
        public UnityEngine.UIElements.VisualElement InspectorTitle;
        
        public UnityEngine.UIElements.TextField NameSpace;
        
        public UnityEngine.UIElements.VisualElement InspectorFoot;
        
        public UnityEngine.UIElements.Button Generate;
        
        public GenUIPanel(UnityEngine.UIElements.TemplateContainer container) : 
                base(container)
        {
            Root = Q<UnityEngine.UIElements.VisualElement>("root");
            Hierarchy = Q<UnityEngine.UIElements.VisualElement>("hierarchy");
            HierarchyTitle = Q<UnityEngine.UIElements.VisualElement>("hierarchy_title");
            RootView = Q<UnityEngine.UIElements.ScrollView>("root_view");
            CutLine = Q<UnityEngine.UIElements.VisualElement>("cut_line");
            Inspector = Q<UnityEngine.UIElements.VisualElement>("inspector");
            InspectorTitle = Q<UnityEngine.UIElements.VisualElement>("inspector_title");
            NameSpace = Q<UnityEngine.UIElements.TextField>("name_space");
            InspectorFoot = Q<UnityEngine.UIElements.VisualElement>("inspector_foot");
            Generate = Q<UnityEngine.UIElements.Button>("generate");
        }
    }
}
